[package]
name = "minilog"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "*"
clap = "^2.27.0"
anyhow = "*"
arrayvec = "*"
zstd = "*"

[profile.release]
debug = true
lto = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "log2mlg"
harness = false
